# Copyright 2021 The terraform-docs Authors.
#
# Licensed under the MIT license (the "License"); you may not
# use this file except in compliance with the License.
#
# You may obtain a copy of the License at the LICENSE file in
# the root directory of this source tree.

FROM docker.io/library/alpine:3.20.3

COPY terraform-docs /usr/local/bin/terraform-docs

ENTRYPOINT ["terraform-docs"]
