package testutil

import (
	"github.com/segmentio/terraform-docs/internal/pkg/tfconf"
	"io/ioutil"
	"os"
	"path/filepath"
	"runtime"
)

// GetModule returns what is generated by the test params
func GetModule(options *tfconf.Options) (*tfconf.Module, error) {
	path, err := GetExampleFolder()
	if err != nil {
		return nil, err
	}
	options.Path = path
	options.OutputValuesPath = path + options.OutputValuesPath

	module, err := tfconf.CreateModule(options)
	if err != nil {
		return nil, err
	}
	return module, err
}

// GetExpected returns 'example' Module and expected Golden file content
func GetExpected(goldenFile string) (string, error) {
	expected, err := readGoldenFile(goldenFile)

	return expected, err
}

// GetExampleFolder returns the path to the examples folder
func GetExampleFolder() (string, error) {
	_, b, _, _ := runtime.Caller(0)
	path := filepath.Join(filepath.Dir(b), "..", "..", "..", "examples")
	if _, err := os.Stat(path); os.IsNotExist(err) {
		return "", err
	}
	return path, nil
}

func readGoldenFile(name string) (string, error) {
	path := filepath.Join(testDataPath(), name+".golden")
	bytes, err := ioutil.ReadFile(path)
	if err != nil {
		return "", err
	}
	return string(bytes), nil
}

func testDataPath() string {
	return filepath.Join("testdata")
}
