# # see: https://terraform-docs.io/user-guide/configuration/version
# version: ">= 0.10, < 0.12"

# see: https://terraform-docs.io/user-guide/configuration/formatter
formatter: markdown table

# see: https://terraform-docs.io/user-guide/configuration/header-from
header-from: doc.txt

# see: https://terraform-docs.io/user-guide/configuration/footer-from
footer-from: footer.md

# see: https://terraform-docs.io/user-guide/configuration/recursive
# recursive:
#   enabled: false
#   path: modules
#   include-main: false

# see: https://terraform-docs.io/user-guide/configuration/sections
sections:
  show:
    - header
    - inputs
    - providers
    - modules
    - footer

# # see: https://terraform-docs.io/user-guide/configuration/content
# content: |-
#   Any arbitrary text can be placed anywhere in the content
#
#   {{ .Header }}
#
#   and even in between sections. also spaces will be preserved:
#
#   - item 1
#     - item 1-1
#     - item 1-2
#   - item 2
#   - item 3
#
#   ## Resources
#   {{ range .Module.Resources }}
#   - {{ .GetMode }}.{{ .Spec }} ({{ .Position.Filename }}#{{ .Position.Line }})
#   {{- end }}
#
#   ## Examples
#
#   ```hcl
#   {{ include "relative/path/to/main.tf" }}
#   ```
#
#   {{ .Providers }}
#
#   and they don't even need to be in the default order
#
#   {{ .Outputs }}
#
#   {{ .Inputs }}

# # see: https://terraform-docs.io/user-guide/configuration/output
# output:
#   file: README.md
#   mode: inject
#   template: |-
#     <!-- BEGIN_TF_DOCS -->
#     The template can be customized with aribitrary markdown content.
#     For example this can be shown before the actual content generated
#     by formatters.
#
#     {{ .Content }}
#
#     You can also show something after it!
#     <!-- END_TF_DOCS -->

# see: https://terraform-docs.io/user-guide/configuration/sort
sort:
  enabled: true
  by: required

# # https://terraform-docs.io/user-guide/configuration/output-values/
# output-values:
#   enabled: false
#   from: ""

# see: https://terraform-docs.io/user-guide/configuration/settings
settings:
  indent: 4
  escape: false
  default: false
  required: false
  type: true
